### ISSUE TITLE
Fireflow module (algosec_provision_network_connectivity) having issues.

### ISSUE THREAD

**Issue by mkiok** [algosec/algosec-ansible-role#13]
I can't see to get algosec_provision_network_connectivity module to work. I followed the given examples but I always hit an error message like the below. The only thing I changed from the examples are the IPs and username/passwords.

I also discovered that if the firewall rule I wanted to add in is already inside the firewall, running this module worked without errors. Although it did not add the rule as it was already present in the firewall.

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_XEmKOm/ansible_module_algosec_provision_network_connectivity.py", line 106, in <module>
    main()
  File "/tmp/ansible_XEmKOm/ansible_module_algosec_provision_network_connectivity.py", line 94, in main
    template=module.params["template"],
  File "/usr/local/lib/python2.7/dist-packages/algosec/api_client.py", line 706, in create_change_request
    soap_traffic_line.action = traffic_line.action.value.api_value
AttributeError: 'ChangeRequestActionInfo' object has no attribute 'value'

fatal: [algosec-server -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):
  File \"/tmp/ansible_XEmKOm/ansible_module_algosec_provision_network_connectivity.py\", line 106, in <module>
    main()
  File \"/tmp/ansible_XEmKOm/ansible_module_algosec_provision_network_connectivity.py\", line 94, in main
    template=module.params[\"template\"],
  File \"/usr/local/lib/python2.7/dist-packages/algosec/api_client.py\", line 706, in create_change_request
    soap_traffic_line.action = traffic_line.action.value.api_value
AttributeError: 'ChangeRequestActionInfo' object has no attribute 'value'
",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
        to retry, use: --limit @/root/.ansible/roles/algosec.algosec/tests/algosectest.retry

**Comment by AlmogCohen** [comment]
Sorry for the inconvenience...

**Comment by mkiok** [comment]
I did the pip install command you mentioned, after which it said Successfully installed algosec-0.9.1...
Howerver, when I ran the same playbook, I got the same error message.

I only was able to get around the issue after manually editing /usr/local/lib/python2.7/dist-packages/algosec/api_client.py

I comment out:
soap_traffic_line.action = traffic_line.action.value.api_value

and replace it with:

soap_traffic_line.action = "1"

=======================
root@server:~/.ansible/roles/algosec.algosec/tests# ansible-playbook -i inventory.ini algosectest.yml

PLAY [Create Traffic Change Request if needed] **************************************************************************************

TASK [Grab the credentials from ansible-vault] **************************************************************************************
ok: [algosec-server]

TASK [Create Traffic Change Request] ************************************************************************************************
changed: [algosec-server -> localhost]

TASK [Print the test results] *******************************************************************************************************
ok: [algosec-server] => {
    "result": {
        "change_request_url": "https://x.x.x.x/FireFlow/Ticket/Display.html?id=36",
        "changed": true,
        "failed": false
    }
}

PLAY RECAP **************************************************************************************************************************
algosec-server             : ok=3    changed=1    unreachable=0    failed=0

**Comment by mkiok** [comment]
May I also ask this, the structure of the yml file:
  - name: Create Traffic Change Request
    # We use delegation to use the local python interpreter (and virtualenv if enabled)
    delegate_to: localhost
    algosec_provision_network_connectivity:
      ip_address: x.x.x.x
      user: admin
      password: algosec
      requestor: xxx
      email: xxx
      sources: '192.168.10.2'
      destinations: '192.168.32.1'
      services: 'tcp/443'
      template: "115: Automatic Traffic Change Request"
    register: result

This would implement one firewall rule. Is there a way to 2 or more firewall rules in the same yml file?
Thanks.

**Comment by AlmogCohen** [comment]
Hmmm weird, I'll add Travis CI testing soon to make sure it does not happen anymore. Issue should be solved though as the package dependencies has been updated. Please let me know if it happens again.
