### ISSUE TITLE
 algosec_provision_network_connectivity.py keep using old algosec ip address

### ISSUE THREAD

**Issue by arkaraung1993** [algosec/algosec-ansible-role#15]
Explanation:

Existing Algosec IP Address: 192.168.10.1
New Algosec IP Address 172.16.1.1

change Algosec IP address in our production Algosec, error log still include existing algosec ip address (192.168.10.1) even though new ip address(172.16.1.1) is defined in the playbook

There is no issue when the rule is already implement, if the is not implement and do traffic change request, there was an error occur. 

---------
Playbook......

- hosts: localhost
  gather_facts: true
  connection: local
  tasks: 

  - name: Create Traffic Change Request
    algosec_provision_network_connectivity:
      ip_address: 172.16.1.1
      user: admin
      password: algosec
      email: arkaraung829@gmail.com
      requestor: SR123456
      template: "115: Automatic Traffic Change Request"
      traffic_lines:
        - action: true
          sources: ["192.168.12.12"]
          destinations: ["16.47.71.62"]
          services: ["HTTPS"]
    register: result
    ignore_errors: true

-----

Error log when run the playbok....

fatal: [ localhost]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger \"suds.client\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_ur63Sq/ansible_module_algosec_provision_network_connectivity.py\", line 133, in <module>\n    main()\n  File \"/tmp/ansible_ur63Sq/ansible_module_algosec_provision_network_connectivity.py\", line 121, in main\n    template=module.params[\"template\"],\n  File \"/usr/lib/python2.7/site-packages/algosec/api_client.py\", line 695, in create_change_request\n    ticket = self.client.factory.create('ticket')\n  File \"/usr/lib/python2.7/site-packages/algosec/api_client.py\", line 604, in client\n    self._client = self._initiate_client()\n  File \"/usr/lib/python2.7/site-packages/algosec/api_client.py\", line 659, in _initiate_client\n    password=self.password,\n  File \"/usr/lib/python2.7/site-packages/suds/client.py\", line 521, in __call__\n    return client.invoke(args, kwargs)\n  File \"/usr/lib/python2.7/site-packages/suds/client.py\", line 581, in invoke\n    result = self.send(soapenv)\n  File \"/usr/lib/python2.7/site-packages/suds/client.py\", line 619, in send\n    description=tostr(e), original_soapenv=original_soapenv)\n  File \"/usr/lib/python2.7/site-packages/suds/client.py\", line 677, in process_reply\n    raise Exception((status, description))\nException: (0, u'Error in requests\\nTraceback (most recent call last):\\n  File \"/usr/lib/python2.7/site-packages/suds_requests.py\", line 16, in wrapper\\n    return f(*args, **kwargs)\\n  File \"/usr/lib/python2.7/site-packages/suds_requests.py\", line 50, in send\\n    headers=request.headers,\\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 559, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 512, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 622, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/usr/lib/python2.7/site-packages/requests/adapters.py\", line 513, in send\\n  
  raise ConnectionError(e, request=request)\\nConnectionError: HTTPSConnectionPool(host=\\'192.168.10.1\\', port=443):
 Max retries exceeded with url: /WebServices/WSDispatcher.pl 
(Caused by NewConnectionError(\\'<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc4e8a59310>: Failed to establish a new connection: [Errno 113] No route to host\\',))\\n')\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by AlmogCohen** [comment]
Sorry I've missed that message. I'd look into this now. I don't think we have any "caching" mechanism implemented anywhere in our code so my first approach would be to look into the Ansible setup... I'll try to see if something comes up in local testing.

**Comment by arkaraung1993** [comment]
Hi Almog,

The issue is solved once we upgrade to algosec 1.3.1.
We would like to ask another issue regarding traffic change request for non-tcp/ip address.

Eg. request Src IP: 192.168.200.1
                   Dest IP: 192.168.100.1
                   Service Port: ping

Algosec module keep reply  no traffic change request eventhough this rule is not in firewall..

**Comment by AlmogCohen** [comment]
I've created a dedicated thread for your question :) Let's try to solve it there ;)
