### ISSUE TITLE
No change request even though rule is not in firewall

### ISSUE THREAD

**Issue by AlmogCohen** [algosec/algosec-ansible-role#18]
Reopening the issue in a dedicated thread as mentioned by @arkaraung1993 in https://github.com/algosec/algosec-ansible-role/issues/15:

> We would like to ask another issue regarding traffic change request for non-tcp/ip address.
> 
> Eg. request Src IP: 192.168.200.1
> Dest IP: 192.168.100.1
> Service Port: ping
> 
> Algosec module keep reply no traffic change request eventhough this rule is not in firewall..

**Comment by AlmogCohen** [comment]
@arkaraung1993 It is important to note that before the Ansible module create the change request with AFF, it checks the traffic simulation with AFA. If the traffic is allowed, by any other firewall rules, then no change request would be created. It does mean that a specific firewall rule will not be created if the traffic for it is already *somehow* allowed as seen by AFA.

Does this make sense? Could this be the issue you mention?

**Comment by arkaraung1993** [comment]
Hi Almog,

Thanks for your answer and appreciate it. First I run traffic simulation query from AFA to confirm the rule is already or not before playbook run and it show block. Than, I run the Playbook and result is keep showing change false and no traffic change request

Please check the output below screenshot.

Query Result.
![image](https://user-images.githubusercontent.com/34660081/55308792-59c9d700-548e-11e9-9e2c-9cd425d1d404.png)

Playbook Output
![image](https://user-images.githubusercontent.com/34660081/55308845-6fd79780-548e-11e9-8bc3-0ababdff197e.png)

**Comment by Morphic99** [comment]
Hi, sorry to jump in but one thing that might be happening here is the Traffic Simulation Query (TSQ) you are running in the screenshot is against a single device - 10.88.78.1. By default, the TSQ you run on a new change request is run against ALL_FIREWALLS.

That might yield a different result to the TSQ against a single firewall. Could you try it from the AFA GUI against ALL_FIREWALLS? In some cases if the map is not complete, you might see something different to what you're expecting here. You can change the group initial plans in a new ticket run on if needed, and use conditional logic so if its run against a certain source or destination, its run against a certain group for example.

**Comment by AlmogCohen** [comment]
@Morphic99 you are awesome! I've never could answer that so well! @arkaraung1993 does that make sense to you?

**Comment by arkaraung1993** [comment]
@Morphic99  It is really helpful for me and Thanks a lot!!. Fist I run TSQ against a single device and show traffic is block. As you said, I run TSQ against ALL_FIREWALL and show traffic is allowed. Than, I suspect Algosec server(10.88.10.102) got something wrong and tried with another Algosec Server and add the same device - 10.88.78.1 and run TSQ against ALL_FIREWALL and show traffic is block. Than, run the playbook and its create traffic change request.

@AlmogCohen Thanks for your reply and really appreciate it. The issue that I opened is resolved.

I got one more issue regarding traffic change request if the user request such kind of request for tcp/udp and no-tcp/up service port in the same rule(eg. tcp/123,esp).  Can i ask here or need to open new issue?

**Comment by AlmogCohen** [comment]
I'd prefer opening a new issue with a matching title as your questions are very good :) I wish people from the future can enjoy them with relevant answer when they will search for it by the title!

Open that and I'd be happy to answer right away. Could you explain about the issue a bit more when you re-open it?

**Comment by AlmogCohen** [comment]
@arkaraung1993 When you re-open it, could you please explain a bit more in detail what is exactly the issue? I'm not sure I understood the question :)
